### ISSUE TITLE
Source files from census.gov missing

### ISSUE THREAD

**Issue by carterpage** [carterpage/census-name-generator#1]
I encountered an error 

Use of uninitialized value $fname in concatenation (.) or string at ./namegen.pl line 43.

**Comment by Logomachist** [comment]
I'm getting the following errors:

$ perl namegen.pl -d 10 >> log.txt
readline() on closed filehandle FILE at namegen.pl line 61.
readline() on closed filehandle FILE at namegen.pl line 61.
readline() on closed filehandle FILE at namegen.pl line 61.
Use of uninitialized value $fname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $lname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $fname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $lname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $fname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $lname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $fname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $lname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $fname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $lname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $fname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $lname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $fname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $lname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $fname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $lname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $fname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $lname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $fname in concatenation (.) or string at namegen.pl line 4  4.
Use of uninitialized value $lname in concatenation (.) or string at namegen.pl line 4  4.

Is this because of the missing census files too?

**Comment by carterpage** [comment]
Yeah, same problem.  I'm trying to find another copy of the file somewhere, then I'll put it in a place I control so they can't yank it again.

**Comment by Logomachist** [comment]
That would be good. For now I got it working using the 1990 census data ("http://www.census.gov/genealogy/www/data/1990surnames/) instead.

**Comment by carterpage** [comment]
I switched out the URL in the code for the 1990 names, so it works again.
